>Korean_Cattle
YAHRAKNILNKPEVNQK------------LTKKALIKEYTEEIERLKRDLA------AAR
EKNGVYISEENFRAMSGKLTVQEEQIVELVEKIA-------------------AVEEELN
RVTELFMDSKNELNQCKSDLQSKTQELET--TQRQLQETKLQLVEEEY--ITSALESTEE
RLH------NAANRLLNTVEE-TTKDVFGLHSKLDRKKAVDQHNAEAQDVFGQNLNSLFN
----------NMEELIKDGSM---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------KQKAMLEVHKTLFGNLLTSSVSALDSITTTALGSLSSIPENVSTLV
SQISNMILKEQSLAAESKTVLQGLINVLKTELLSS-------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>Fire_belly_newt
------------------------------------------------------------
-----------------------------------------------------------A
PDGEFTWDEDPLAGIIPRTLHQIFEKLSENGTEFSVKVSLLEIYNEELFDLLSPCPDVNE
RLQMFDDPRNKRGVIIKGLEEVTVHNKNEVYQILERGAAKRTTASTLMNAYSSRSHSVFS
VTIHMKETTVDGEELVKXGKLNLVXLAGSENIGRSGAVDKRAREAGNINQSLLTLGRVIT
ALXERTPHIPYRXSKLTRILQXSLGXXTKTSIIATXSPASINXEETLSTLXYAYRAKNIM
NK----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>Red_Junglefowl
------------------------------------------------------------
-----------FRAQAKQIDVYRSVVCPILDEVIMGYNCTVFAYGQTGTGKTFTMEGERS
PNEEYTWEEDPLAGIIPRTLHQIFEKLTENGTEFSVKVSLLEIYNEELFDLLNPAPDVGE
RLQMFDDPRNKRGVIIKGLEEVTVHNKNEVYQILERGAAKRTTAATYMNAYSSRSHSVFS
ITIHMKETTVDGEELVKIGKLNLVDLAGSENIGRSGAVDKRAREAGNINQSLLTLGRVIS
ALVERAPAYSIQES----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>Westerned_Clawed_Frog
------------------------------------------------------------
--KKTYTFDMVFGPAAKQIDVYRSVVCPILDEVIMGYNCTVFAYGQTGTGKTFTMEGERS
ADEEFTWEQDPLAGIIPRTLHQIFEKLSENGTEFSVKVSLLEIYNEELFDLLSPSPDVGE
RLQMFDDPRNKRGVIIKGLEEVSVHNKDEVYHILERGAARRKTASTLMNAYSSRSHSVFS
VTIHMKETTVDGEELVKIGKLNLVDLAGSENIGRSGAVDKRAREAGNINQSLLTLGRVIT
ALVERAPHIPYRESKLTRILQDSLG-----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>Fathead_Minnow
---------------GRNIQVVVRCRPFNTVERKSASHTVVECDQNKKELTVRTGGATDK
SSRKTYTFDMVFGPSAKQIDVYRSVVCPILDEVIMGYNCTIFAYGQTGTGKTFTMEGDRS
PNEEFTWEEDPLAGIIPRTLHQIFEKLSNNGTEFSVKVSLLEIYNEELFDLLSPAPDVTE
RLQLFDDPRNKRGVTIKGLEEVTVHNKNEVYQILERGAAKRKTASTLMNAYSSRSHSVFS
VTIHMKEITLDGEELVKIGKLNLVDLAGSENIGRSGAVDKRAREAGNINQSLLTLGRVIK
AL----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>House_mouse
----------------------------------------------RKEVSVRTAGLTDK
TSKKTYTFDMVFGASTKQIDVYRSVVCPILDEVIMGYNCTIFAYGQTGTGKTFTMEGERS
PNEVYTWEEDPLAGIIPRTLHQIFEKLTDNGTEFSVKVSLLEIYNEELFDLLSPSSDVSE
RLQMFDDPRNKRGVIIKGLEEITVHNKDEVYQILEKGAAKRTTAATLMNAYSSRSHSVFS
VTIHMKXTTIDGEELVKIGKLNLVDLAGSENIGRSGAVDKRAREA---------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>Human_KIF11
MASQPNSSAKKKEEKGKNIQVVVRCRPFNLAERKASAHSIVECDPVRKEVSVRTGGLADK
SSRKTYTFDMVFGASTKQIDVYRSVVCPILDEVIMGYNCTIFAYGQTGTGKTFTMEGERS
PNEEYTWEEDPLAGIIPRTLHQIFEKLTDNGTEFSVKVSLLEIYNEELFDLLNPSSDVSE
RLQMFDDPRNKRGVIIKGLEEITVHNKDEVYQILEKGAAKRTTAATLMNAYSSRSHSVFS
VTIHMKETTIDGEELVKIGKLNLVDLAGSENIGRSGAVDKRAREAGNINQSLLTLGRVIT
ALVERTPHVPYRESKLTRILQDSLGGRTRTSIIATISPASLNLEETLSTLEYAHRAKNIL
NKPEVNQKLTKKALIKEYTEEIERLKRDLAAAREKNGVYISEENFRVMSGKLTVQEEQIV
ELIEKIGAVEEELNRVTELFMDNKNELDQCKSDLQNKTQELETTQKHLQETKLQLVKEEY
ITSALESTEEKLHDAASKLLNTVEETTKDVSGLHSKLDRKKAVDQHNAEAQDIFGKNLNS
LFNNMEELIKDGSSKQKAMLEVHKTLFGNLLSSSVSALDTITTVALGSLTSIPENVSTHV
SQIFNMILKEQSLAAESKTVLQELINVLKTDLLSSLEMILSPTVVSILKINSQLKHIFKT
SLTVADKIEDQKKELDGFLSILCNNLHELQENTICSLVESQKQCGNLTEDLKTIKQTHSQ
ELCKLMNLWTERFCALEEKCENIQKPLSSVQENIQQKSKDIVNKMTFHSQKFCADSDGFS
QELRNFNQEGTKLVEESVKHSDKLNGNLEKISQETEQRCESLNTRTVYFSEQWVSSLNER
EQELHNLLEVVSQCCEASSSDITEKSDGRKAAHEKQHNIFLDQMTIDEDKLIAQNLELNE
TIKIGLTKLNCFLEQDLKLDIPTGTTPQRKSYLYPSTLVRTEPREHLLDQLKRKQPELLM
MLNCSENNKEETIPDVDVEEAVLGQYTEEPLSQEPSVDAGVDCSSIGGVPFFQHKKSHGK
DKENRGINTLERSKVEETTEHLVTKSRLPLRAQINL
>Wild_boar
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------NKRGVIIKGLEEITVHNKNEVYQILEKGAAKRTTAATLMNAYSSRSHSVFS
VTIHMKETTVDGEELVKIGKLNLVDLAGSENIGRSGAVDKRAREAGNINQSLLTLGRVIT
ALVERTPHVPYRESKLTRILQDSLGGRTRTSIIATISPASLNLEETLSTLEYAHRAKNIL
NKPEVNQKLTKKALIKEYTEEIERLKRDLAAAREKNGVYISEENFRAMSGKLTVQEEQIV
ELVEKIAAIAEELNRVTELFMDNKNELDQCKSDLQNKTQEL-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
